services:
    ao-analytics-db:
        container_name: ao-analytics-db
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
        restart: unless-stopped
        ports:
            - 5432:5432
        volumes:
            - ./data:/var/lib/postgresql/data
