services:
  ao-analytics-db:
    container_name: ao-analytics-db
    image: timescale/timescaledb:latest-pg16
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ao
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./data/:/var/lib/postgresql/data/